version: "3"
services:
  db:
    image: mariadb:10.3
    environment:
      MYSQL_DATABASE: "todo_list"
      MYSQL_ROOT_PASSWORD: "PASSWORD"
    ports:
      - "3306:3306"
    volumes:
      - django-datavolume:/var/lib/mysql
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8030:8000
    links:
      - db
    volumes:
      - /home/player1/Documents/Content/coding_projects/django_docker_example/src:/django_project
    entrypoint: /docker-entrypoint.sh
volumes:
  django-datavolume:
